interface Skill {
  id: number
  name: string
  icon: string
  level: number
  category: string
  color: string
}

export const skills: Skill[] = [
  {
    id: 1,
    name: 'React',
    icon: 'https://upload.wikimedia.org/wikipedia/commons/a/a7/React-icon.svg',
    level: 70,
    category: 'Frontend',
    color: '#61dafb',
  },
  {
    id: 2,
    name: 'JavaScript',
    icon: 'https://cdn.worldvectorlogo.com/logos/javascript-1.svg',
    level: 80,
    category: 'Frontend',
    color: '#61dafb',
  },
  {
    id: 3,
    name: 'TypeScript',
    icon: 'https://cdn.worldvectorlogo.com/logos/typescript.svg',
    level: 70,
    category: 'Frontend',
    color: '#61dafb',
  },
  {
    id: 3,
    name: 'Vue3',
    icon: 'https://vuejs.org/images/logo.png',
    level: 40,
    category: 'Frontend',
    color: '#61dafb',
  },
  {
    id: 4,
    name: 'Next',
    icon: 'https://cdn.worldvectorlogo.com/logos/nextjs-2.svg',
    level: 70,
    category: 'Frontend',
    color: '#61dafb',
  },
  {
    id: 5,
    name: 'HTML5',
    icon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/HTML5_Badge.svg/2048px-HTML5_Badge.svg.png',
    level: 95,
    category: 'Frontend',
    color: '#61dafb',
  },
  {
    id: 6,
    name: 'CSS',
    icon: 'https://upload.wikimedia.org/wikipedia/commons/6/62/CSS3_logo.svg',
    level: 90,
    category: 'Styling',
    color: '#f7df1e',
  },
  {
    id: 7,
    name: 'Tailwind CSS',
    icon: 'https://www.vectorlogo.zone/logos/tailwindcss/tailwindcss-icon.svg',
    level: 90,
    category: 'Styling',
    color: '#f7df1e',
  },
  {
    id: 8,
    name: 'Bootstrap',
    icon: 'https://v5.getbootstrap.com/docs/5.0/assets/brand/bootstrap-logo-shadow.png',
    level: 80,
    category: 'Styling',
    color: '#f7df1e',
  },
  {
    id: 9,
    name: 'Ant Design / Shadcn UI',
    icon: 'https://raw.githubusercontent.com/shadcn/ui/main/apps/www/public/favicon.ico',
    level: 80,
    category: 'Styling',
    color: '#f7df1e',
  },
  {
    id: 10,
    name: 'Framer Motion',
    icon: 'https://cdn.worldvectorlogo.com/logos/framer-motion.svg',
    level: 80,
    category: 'Styling',
    color: '#f7df1e',
  },
  {
    id: 11,
    name: 'Node',
    icon: 'https://miro.medium.com/v2/resize:fit:1000/1*TGwJKcxY8kGEenRLLedeLw.png',
    level: 60,
    category: 'Backend',
    color: '#339933',
  },
  {
    id: 12,
    name: 'Express',
    icon: 'https://www.svgrepo.com/show/353724/express.svg',
    level: 50,
    category: 'Backend',
    color: '#339933',
  },
  {
    id: 13,
    name: 'MySQL',
    icon: 'https://i0.wp.com/saixiii.com/wp-content/uploads/2017/04/mysql.png?ssl=1',
    level: 50,
    category: 'Backend',
    color: '#339933',
  },
  {
    id: 14,
    name: 'Nest',
    icon: 'https://nestjs.com/img/logo-small.svg',
    level: 40,
    category: 'Backend',
    color: '#339933',
  },
  {
    id: 15,
    name: 'Prisma',
    icon: 'https://cdn.worldvectorlogo.com/logos/prisma-2.svg',
    level: 80,
    category: 'Backend',
    color: '#339933',
  },
  {
    id: 16,
    name: 'Version Control Git',
    icon: 'https://git-scm.com/images/logos/downloads/Git-Icon-1788C.png',
    level: 90,
    category: 'Backend',
    color: '#339933',
  },
  {
    id: 17,
    name: 'Swagger',
    icon: 'https://static1.smartbear.co/swagger/media/assets/images/swagger_logo.svg',
    level: 70,
    category: 'Backend',
    color: '#339933',
  },
  {
    id: 18,
    name: 'Postman',
    icon: 'https://www.svgrepo.com/show/354202/postman-icon.svg',
    level: 80,
    category: 'Backend',
    color: '#339933',
  },
]
